### PR TITLE
Make dragonboat work with Pebble v1.0.0

### PR DESCRIPTION
**Pull request by tylerwilliams**
(Based off of https://github.com/lni/vfs/pull/3)

### CODE REVIEW

**Comment by lni** [comment]
Could you please have a look at the above failed tests? The go version might need to be bumped to go 1.21, there seem to be other issues as well. 

Thanks.

**Comment by tylerwilliams** [comment]
> Could you please have a look at the above failed tests? The go version might need to be bumped to go 1.21, there seem to be other issues as well.
> 
> Thanks.

I'm having a difficult time making these tests pass without the vfs library change being committed. Could you take a look at [that one](https://github.com/lni/vfs/pull/3) first?

**Comment by tylerwilliams** [comment]
> > Could you please have a look at the above failed tests? The go version might need to be bumped to go 1.21, there seem to be other issues as well.
> > Thanks.
> 
> I'm having a difficult time making these tests pass without the vfs library change being committed. Could you take a look at [that one](https://github.com/lni/vfs/pull/3) first?

Ah, please ignore my last comment. I see this is down to a mac v linux issue. Will take a look tomorrow if I get time.

**Comment by mostcute** [comment]
it's just rand pkg changed since go1.20.0

**Comment by lni** [comment]
Thanks @mostcute.  

I guess we can just bump the required Go version to v1.20.

**Comment by lni** [comment]
I've bumped dragonboat's required go version to v1.20. 

@tylerwilliams would you like to merge master into your branch and give it a go? Thanks.

**Comment by tylerwilliams** [comment]
closing in favor of https://github.com/lni/dragonboat/pull/341

**Pull request closed without merging**
