### PR TITLE
Beta 3.0 cppbinding

### PR DESCRIPTION
**Pull request by JasonYuchen**
beta 3.0 cpp binding for review

### CODE REVIEW

**Comment by lni** [comment]
Thanks a lot for working on this. 

I had a quick review on the changes, below are the first few minor issues I'd like to discuss - 

1. The FIXME (https://github.com/JasonYuchen/dragonboat/blob/beta-3.0-cppbinding/internal/cpp/wrapper.go#L901) in internal/cpp/wrapper.go need to be addressed. It causes IO error on the remote side when it is not handled. 

2. The update() method in OnDiskStateMachine and ConcurrentStateMachine only takes a single entry as the input. This will prevent multiple entries to be batched. I think the C++ binding should allow a list of entries to be handled by the update method, just like its Go native method. 

3. PrepareSnapshot() returns a PrepareSnapshotResult with the following definition. We actually want to return an arbitrary user type (interface{} in Go). Maybe use C++ template here?  

typedef struct
{
  char *result;
  size_t size;
  int errcode;
} PrepareSnapshotResult; 

4. Similar to the item 3 above, the signature of the Lookup() method has been updated in v3.0 to take and return an interface{}. Maybe use template for that as well? 

5. The interface{} returned by PrepareSnapshot will be immediately passed to the SaveSnapshot method, associated resources are supposed to be released inside the SaveSnapshot method before its return. freePrepareSnapshotResult is thus not required. 

6. A few other methods, e.g. SaveSnapshot, RecoverFromSnapshot and Sync, return error in their Go version. For NodeHost's wrapper, such returned errors are being represented as class Status. Maybe use class Status (with some extension) as SaveSnapshot, RecoverFromSnapshot and Sync's returned results as well?  

Again - thank you for working on this. Let's spend some time together on this to make the C++ binding great again. ;)

**Comment by JasonYuchen** [comment]
Thanks for your review.

1. fixed

2. batchedUpdate is supported on all three kinds of statemachines

3/4/5. lookup/prepareSnapshot/saveSnapshot now use ``void *`` to hold an arbitrary type which may be improved in the future. freeLookupResult/freePrepareSnapshotResult are removed.

All tests in nodehost_test.cpp and wrapper_test.go are updated to use the new interfaces.

**Comment by JasonYuchen** [comment]
Maybe I should avoid `void **result` in read methods.
How about `ReadResult NodeHost::SyncRead(...)` ?
```
struct ReadResult {
    Status s;
    void *result;
};
```

**Comment by lni** [comment]
@JasonYuchen thanks for the update.

I think for now we can keep the old interface that take/returns a char*.

**Comment by JasonYuchen** [comment]
RaftEventListener is a nice feature which is also supported in cpp binding now!

**Pull request merged**
