### PR TITLE
support direct cpp statemachine factory

### PR DESCRIPTION
**Pull request by JasonYuchen**
it is sometimes inconvenient (not cool) to build a separate .so file to hold a CPP statemachine

so I added some functions to support a direct statemachine factory function

for example, in cpphelloworld/helloworld.cpp
```
+ extern "C" CPPStateMachine *CreateDragonboatFactoryStateMachine(uint64_t clusterID,
+   uint64_t nodeID)
+ {
+   CPPStateMachine *cds = new CPPStateMachine;
+   cds->sm = new HelloWorldStateMachine(clusterID, nodeID);
+   return cds;
+ }

....

- status = nh->StartCluster(peers, false, "dragonboat-cpp-plugin-cpphelloworld.so", config);
+ status = nh->StartCluster(peers, false, CreateDragonboatFactoryStateMachine, config);

```
just parse a factory function, no need to build a separate .so file

### CODE REVIEW

**Comment by lni** [comment]
I think it is a reasonable proposal. Before it can be merged, there are two minor issues to be addressed -

* StartClusterUsingFactory takes the factory input parameter as an uint64, any better alternative than that, maybe use pointer type? 
* please add tests to cover the new API, existing tests are available in binding/tests/nodehost_tests.cpp

**Comment by JasonYuchen** [comment]
Thanks for the review

I have tested it in cpphelloworld and will add tests according to the nodehost_tests.cpp
Maybe unsafe.Pointer is a better choice

I am working on it and will make a new PR when everything is ok

**Comment by JasonYuchen** [comment]
The added cases are the same as the original ones for .so, with minor modifications in [TwoNodeHostRequired](https://github.com/lni/dragonboat/pull/58/commits/dc0b41593e46f0afe7160dfd3233f7bd2cd35f43#diff-2bebc7858d7b059736d1a87356bfd174L160)

have passed the new cppwrapper tests, thanks

**Comment by lni** [comment]
The new NodeHost::StartCluster is largely a copy-paste job of the existing one, any chance to refactor it a bit to avoid the duplicated code?  

I don't think all those tests have to be replicated to use the new StartClusterUsingFactory method,  
the following new tests seem to be relevant - 

ClusterCanBeAddedAndRemoved_CppFactory
ClusterCanNotBeAddedTwice_CppFactory
JoiningWithPeerListIsNotAllowed_CppFactory
RestartingWithDifferentPeerSetIsNotAllowed_CppFactory
JoinAnInitialPeerIsNotAllowed_CppFactory
RestartPreviouslyJoinedNodeWithPeerSetIsNotAllowed_CppFactory
ProposalAndReadCanBeMade_CppFactory

Any particular reason why other new tests should be added as well?   

Please also avoid using '_' in test names.

**Comment by JasonYuchen** [comment]
Yes, I will refactor the API to remove the duplicated code and update the tests (adding all those cases is just to make sure the new API is correct, I will follow your advice. Thanks!)

BTW, `struct RaftConfig` has `MaxMessageSize` and `MaxInflightMessages` which are not included in `class Config`, moreover `config.go` has a `MaxInMemLogSize`, why is the difference?

**Comment by lni** [comment]
MaxMessageSize was configurable in previous versions, but it was later removed. MaxInflightMessages was a configurable parameter similar to the inflight message limit concept in etcd raft, but it was never implemented. I will remove both of them.

MaxInMemLogSize is for the coming v3.0 release, it has not been supported by the C++ binding. The C++ binding is currently targeting the v2.1.x release. Will be great if there is more community input to make all v3.0 features covered. Please let me know if you are interested. :)

**Comment by JasonYuchen** [comment]
Definitely! I'd like to try my best.  :)

**Comment by JasonYuchen** [comment]
Minor modification, plan to support v3.0 features in C++ bindings when I have a better understanding. Thanks!

**Comment by lni** [comment]
Merged with some minor cleanups.

**Pull request merged**
